// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service.PushNotification.Postgres;

#nullable disable

namespace Service.PushNotification.Postgres.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211115121851_UseJsonProperty-1")]
    partial class UseJsonProperty1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pushnotification")
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Service.PushNotification.Postgres.NotificationHistoryDbEntity", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<List<string>>("Params")
                        .HasColumnType("jsonb")
                        .HasColumnName("ParamsJson");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("NotificationId");

                    b.ToTable("notification_history", "pushnotification");
                });

            modelBuilder.Entity("Service.PushNotification.Postgres.NotificationStatusDbEntity", b =>
                {
                    b.Property<Guid>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HistoryDbEntityNotificationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("StatusId");

                    b.HasIndex("HistoryDbEntityNotificationId");

                    b.ToTable("notification_statuses", "pushnotification");
                });

            modelBuilder.Entity("Service.PushNotification.Postgres.NotificationStatusDbEntity", b =>
                {
                    b.HasOne("Service.PushNotification.Postgres.NotificationHistoryDbEntity", "HistoryDbEntity")
                        .WithMany("DeliveryStatuses")
                        .HasForeignKey("HistoryDbEntityNotificationId");

                    b.Navigation("HistoryDbEntity");
                });

            modelBuilder.Entity("Service.PushNotification.Postgres.NotificationHistoryDbEntity", b =>
                {
                    b.Navigation("DeliveryStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
